version: '3.1'
services:
  service:
    image: $IMAGE_NAME
    container_name: $SERVICE_NAME
    env_file: .env
    environment:
      - STORER_DATA_FILE=$STORER_DATA_FILE
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - SERVICE=$SERVICE_NAME
      - VERSION=$SERVICE_VERSION
      - PORT=$SERVICE_GRPC_PORT
