apiVersion: v1
kind: Service
metadata:
  name: storer
  labels:
    app: storer
    version: 1.0.0
spec:
  ports:
  - name: grpc
    port: 10080
    targetPort: grpc
  selector:
    app: storer
    version: 1.0.0
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: storer
      version: 1.0.0
  template:
    metadata:
      labels:
        app: storer
        version: 1.0.0
    spec:
      containers:
      - name: storer
        image: svc-storer:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: storer-env-config
        ports:
        - containerPort: 10080
          name: grpc
        resources:
          requests:
            cpu: 100m
