apiVersion: v1
kind: Service
metadata:
  name: ingestor
  labels:
    app: ingestor
    version: 1.0.0
spec:
  ports:
  - name: grpc
    port: 10080
    targetPort: grpc
  selector:
    app: ingestor
    version: 1.0.0
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ingestor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ingestor
      version: 1.0.0
  template:
    metadata:
      labels:
        app: ingestor
        version: 1.0.0
    spec:
      containers:
      - name: ingestor
        image: svc-ingestor:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: ingestor-env-config
        ports:
        - containerPort: 10080
          name: grpc
        resources:
          requests:
            cpu: 100m
